### ISSUE TITLE
Salt field not long enough (> 50 characters)

### ISSUE THREAD

**Issue by denk-n** [jibon57/BigBlueButton_for_Joomla#13]
Our bbb server has a shared secret with more than 50 characters, so the last part is cut when using the configuration form.

I tried entering the salt value manually via database input, but I couldn't get the extension to connect to the server. I only got the "Sorry, can't login. [...]" message when I entered name and password. I couldn't pinpoint the exact breaking point while looking through the code. Sorry.

I know that the server url and salt data is correct, because moodle and wordpress plugins are working.

**Comment by jibon57** [comment]
Sorry, didn't notice this. If still having problem then you can edit this value:

https://github.com/jibon57/BigBlueButton_for_Joomla/blob/7bb384f5dffe92ffdeb16df6be413d19982acb09/packages/com_bigbluebutton/admin/config.xml#L49
