### ISSUE TITLE
BigBlueButton Login Display

### ISSUE THREAD

**Issue by alexnya** [jibon57/BigBlueButton_for_Joomla#2]
Hi,

I don't know if this is too late or not but I figured this is the best place to ask. I have Joomla and BigBlueButton running fine on my server. When I try to integrate the two by installing the module from this link: https://www.hoicoimasti.com/products/joomla-extensions/9-bigbluebutton-extension-for-joomla.html, I'm able to install it and publish the module in Joomla. However, I'm not able to see the BigBlueButton meeting login on the site login page. I put my server URL and salt in Options, I published the BigBlueButton module under Modules, and I created a meeting on the Joomla Administrator page. I just need to know how to get the BigBlueButton meeting login to show on my Joomla site page.

Thank you,
Alex Nyamweya

**Comment by jibon57** [comment]
@alexnya after creating meeting you should be able to get the list of meetings in module. You will need to use that module for login. I have started working for new version with some extended features.

**Comment by alexnya** [comment]
Yes I figured it out! I just had to adjust the position of where the bigbluebutton login appears on the joomla login page. Thank you so much!
